spring.application.name=ecommerce-platform-be

spring.datasource.url=jdbc:postgresql://localhost:5432/ecommerce
spring.datasource.username=postgres
spring.datasource.password=dcj123

spring.jpa.hibernate.ddl-auto=update

